// The mark: the drawing on the card against the drawing in the repository, and when a new one
// happens.
//
// Two halves, and they are two different kinds of claim.
//
// The drawing is a bitmask in `shaders/logo.glsl`, generated by `tools/logo-table.ps1` from
// `assets/logo.txt`. Two copies of a drawing is one place for them to disagree, and a logo that is
// wrong only on the card is the kind of fault that survives a whole release — so every one of the
// 25,600 pixels is checked here, exactly as the typeface is in test_font.cpp.
//
// The rest is `src/ui/logo.hpp`: which combination is being drawn and when that changes. None of
// that can be seen in a screenshot at all — a press that quietly chose the same seed again and a
// press that did nothing look identical, and so do a morph that never finishes and a morph that
// never started.

#include <algorithm>
#include <cstdlib>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include "doctest/doctest.h"
#include "ui/logo.hpp"
#include "ui/logo_marks.hpp"

using namespace ws;
using namespace ws::ui;

namespace {

std::string read_file(const std::string& path) {
    std::ifstream file(path, std::ios::binary);
    REQUIRE_MESSAGE(file.good(), "could not open " << path);
    std::stringstream buffer;
    buffer << file.rdbuf();
    return buffer.str();
}

std::string shader_source() { return read_file(std::string(WS_SHADER_SOURCE_DIR) + "/logo.glsl"); }

// The drawing as it is written down: one character per pixel, '#' is mark.
struct Drawing {
    u32 width = 0;
    u32 height = 0;
    std::vector<bool> on;

    bool at(u32 x, u32 y) const { return on[static_cast<usize>(y) * width + x]; }
};

Drawing read_drawing() {
    const std::string text = read_file(std::string(WS_ASSET_SOURCE_DIR) + "/logo.txt");
    std::stringstream lines(text);
    std::string line;
    Drawing drawing;
    while (std::getline(lines, line)) {
        if (!line.empty() && line.back() == '\r') line.pop_back();
        if (line.empty() || line[0] == '#') {
            // A comment is a line that starts with '#' AND is not a row of the drawing, which every
            // row of a 160-wide bitmap is. The size line comes first, so a row is anything as long
            // as the drawing says it is.
            if (drawing.width == 0 || line.size() != drawing.width) continue;
        }
        if (line.rfind("size ", 0) == 0) {
            std::stringstream parts(line.substr(5));
            parts >> drawing.width >> drawing.height;
            continue;
        }
        if (drawing.width == 0 || line.size() != drawing.width) continue;
        for (char c : line) drawing.on.push_back(c == '#');
    }
    REQUIRE(drawing.width == 160u);
    REQUIRE(drawing.height == 160u);
    REQUIRE(drawing.on.size() == static_cast<usize>(drawing.width) * drawing.height);
    return drawing;
}

// One `const uint kName = 24u;` out of the shader.
u32 shader_count(const std::string& text, const std::string& name) {
    const usize at = text.find("const uint " + name + " = ");
    REQUIRE_MESSAGE(at != std::string::npos, "shaders/logo.glsl declares no " << name);
    return static_cast<u32>(std::strtoul(text.c_str() + at + 11 + name.size() + 3, nullptr, 10));
}

}  // namespace

TEST_CASE("the card's drawing is the drawing in the repository") {
    const Drawing drawing = read_drawing();
    const std::string text = shader_source();

    const usize begin = text.find("kLogoBits[800] = uint[800](");
    REQUIRE(begin != std::string::npos);
    const usize end = text.find("--- end generated ---", begin);
    REQUIRE(end != std::string::npos);

    // The dimensions the shader believes, which is what its indexing is built out of.
    CHECK(shader_count(text, "kLogoAnimations") == kLogoAnimations);
    const usize width_at = text.find("const int kLogoWidth = ");
    const usize height_at = text.find("const int kLogoHeight = ");
    REQUIRE(width_at != std::string::npos);
    REQUIRE(height_at != std::string::npos);
    CHECK(std::strtoul(text.c_str() + width_at + 23, nullptr, 10) == drawing.width);
    CHECK(std::strtoul(text.c_str() + height_at + 24, nullptr, 10) == drawing.height);

    std::vector<u32> words;
    usize at = begin;
    while (true) {
        at = text.find("0x", at);
        if (at == std::string::npos || at > end) break;
        words.push_back(static_cast<u32>(std::strtoul(text.c_str() + at + 2, nullptr, 16)));
        at += 2;
    }
    // Five words a row, one bit a pixel, thirty-two pixels to a word.
    const u32 per_row = (drawing.width + 31) / 32;
    REQUIRE(words.size() == static_cast<usize>(per_row) * drawing.height);

    u32 mark_pixels = 0;
    u32 wrong = 0;
    for (u32 y = 0; y < drawing.height; ++y) {
        for (u32 x = 0; x < drawing.width; ++x) {
            const u32 word = words[static_cast<usize>(y) * per_row + (x >> 5)];
            const bool packed = ((word >> (x & 31u)) & 1u) != 0u;
            // Reported rather than asserted per pixel: 25,600 CHECKs that all pass is 25,600 lines
            // of nothing, and the first offending pixel is what somebody actually needs.
            if (packed != drawing.at(x, y)) {
                if (wrong == 0) INFO("first wrong pixel " << x << "," << y);
                ++wrong;
            }
            if (drawing.at(x, y)) ++mark_pixels;
        }
    }
    CHECK(wrong == 0u);
    // And it is a drawing rather than an empty square or a full one, which is the failure a
    // generator that silently wrote nothing would produce and every pixel comparison above would
    // pass in silence.
    CHECK(mark_pixels > 4000u);
    CHECK(mark_pixels < static_cast<u32>(drawing.width * drawing.height) - 4000u);
}

TEST_CASE("every combination the counts allow is a combination the card draws") {
    // Trap 7 in the handover, in a shader: *"nothing here" and "I could not fit it" must never be
    // the same answer.* Raising a count without writing the branch to go with it gives a seed that
    // draws nothing at all, and nothing anywhere says so — the mark simply comes up blank for one
    // player in twenty-four.
    const std::string text = shader_source();

    CHECK(shader_count(text, "kLogoAnimations") == kLogoAnimations);
    CHECK(shader_count(text, "kLogoPatterns") == kLogoPatterns);
    CHECK(shader_count(text, "kLogoPalettes") == kLogoPalettes);
    CHECK(shader_count(text, "kLogoArrangements") == kLogoArrangements);
    CHECK(shader_count(text, "kLogoTransitions") == kLogoTransitions);
    // The slices, and the words the host sends about them. The orders and the keys are not here
    // because they are not the card's: the sort runs on the host now (see ui/logo.hpp) and the card
    // reads the answer, so what has to agree between the two is the LAYOUT of that answer.
    CHECK(shader_count(text, "kLogoLanes") == kLogoLanes);
    // The frame's layout is written as an expression on the card rather than as a number, so what is
    // checked is the expression: three words of header and then one a slice, which is what
    // `DrawList::logo` writes and what `logo_draw` strides by to find the outgoing seed's frame.
    CHECK(text.find("const uint kLogoFrameWords = 3u + kLogoLanes;") != std::string::npos);
    CHECK(kLogoFrameWords == 3u + kLogoLanes);

    // Each of the three is a chain of `which == Nu` (or `scheme == Nu`) with the last index falling
    // through to the else, so the branches to look for are 0 to count-2 and the count itself must
    // not appear. Searched inside ONE function each: the animations and the patterns both call their
    // choice `which`, so a search over the whole file would let a missing pattern be covered by the
    // animation of the same number, which is the exact fault this is here to catch.
    const auto branches = [&](const std::string& variable, u32 count, const std::string& from,
                              const std::string& to) {
        const usize begins = text.find(from);
        const usize ends = text.find(to);
        REQUIRE_MESSAGE(begins != std::string::npos, from);
        REQUIRE_MESSAGE(ends != std::string::npos, to);
        REQUIRE(begins < ends);
        const std::string body = text.substr(begins, ends - begins);
        for (u32 index = 0; index + 1 < count; ++index) {
            const std::string needle = variable + " == " + std::to_string(index) + "u";
            INFO(from << ": " << needle);
            CHECK(body.find(needle) != std::string::npos);
        }
        const std::string past = variable + " == " + std::to_string(count) + "u";
        INFO(from << ", out of range: " << past);
        CHECK(body.find(past) == std::string::npos);
    };
    branches("which", kLogoPatterns, "float logo_pattern_one(", "float logo_pattern_mix(");
    branches("which", kLogoAnimations, "LogoMotion logo_motion_one(", "LogoMotion logo_motion(");
    branches("scheme", kLogoPalettes, "vec3 logo_palette(", "float logo_pattern_one(");
    branches("which", kLogoArrangements, "LogoFold logo_fold(", "// --- the whole mark");
    branches("which", kLogoTransitions, "LogoFade logo_transition(", "// The mark. `local` is");

    // And the pick each of those chains is fed by is bounded BY those counts rather than by a number
    // somebody typed twice.
    CHECK(text.find("logo_pick(seed, 21u, kLogoPatterns)") != std::string::npos);
    CHECK(text.find("logo_pick(seed, 51u, kLogoPatterns)") != std::string::npos);
    CHECK(text.find("logo_pick(seed, 31u, kLogoAnimations)") != std::string::npos);
    CHECK(text.find("logo_pick(seed, 41u, kLogoAnimations)") != std::string::npos);
    CHECK(text.find("logo_pick(seed, 11u, kLogoPalettes)") != std::string::npos);
    CHECK(text.find("logo_pick(seed, 81u, kLogoArrangements)") != std::string::npos);
    CHECK(text.find("logo_pick(seed, 91u, kLogoTransitions)") != std::string::npos);

    // What the header of that file claims, in words, is what the numbers here multiply out to. A
    // documented count that has drifted from the code is the one kind of comment that is worse than
    // no comment.
    CHECK(kLogoCombinations == 3981312000ull);
    CHECK(text.find("3,981,312,000") != std::string::npos);

    CHECK(kLogoAxes == 2u);

    // The one constant the host and the card BOTH act on rather than merely agree about: the host
    // inflates the command's rectangle by it and the shader divides it back out. A disagreement is
    // not a wrong colour, it is the drawing at the wrong size inside a box that is still there.
    const usize reach_at = text.find("const float kLogoReach = ");
    REQUIRE(reach_at != std::string::npos);
    CHECK(std::strtod(text.c_str() + reach_at + 25, nullptr) == doctest::Approx(kLogoReach));
    CHECK(kLogoReach > 1.0f);   // at one there is no room at all, which is the box coming back
}

TEST_CASE("the mark's slices are one per voxel row, and the table of their weights is the drawing") {
    // The host cannot see the drawing — it is a bitmask on the card — so the one property of it the
    // sort needs is generated into a table. If that table drifts from the picture, a mark sorted by
    // weight is sorted by the weight of a drawing that no longer exists, and nothing anywhere says so.
    const Drawing drawing = read_drawing();
    REQUIRE(kLogoLanes == drawing.width);
    REQUIRE(kLogoLanes == drawing.height);

    u32 total_rows = 0;
    u32 total_columns = 0;
    for (u32 lane = 0; lane < kLogoLanes; ++lane) {
        u32 row = 0;
        u32 column = 0;
        for (u32 other = 0; other < kLogoLanes; ++other) {
            if (drawing.at(other, lane)) ++row;
            if (drawing.at(lane, other)) ++column;
        }
        INFO("lane " << lane);
        CHECK(kLogoRowMark[lane] == row);
        CHECK(kLogoColumnMark[lane] == column);
        total_rows += row;
        total_columns += column;
    }
    // Both count the same voxels from two directions, so they cannot disagree about the total.
    CHECK(total_rows == total_columns);
    CHECK(total_rows > 4000u);
}

TEST_CASE("every sorting algorithm sorts, and a partial run is a prefix of a whole one") {
    // This is the whole reason the sort is on the host. A shader cannot be asked whether its array
    // came out sorted; this can, for all ten of them, at every seed.
    std::vector<bool> algorithms(kLogoOrders, false);
    for (u32 seed = 1; seed <= 400; ++seed) {
        // Walk a whole cycle rather than guessing an instant inside one: where a seed is in its own
        // cycle is a function of the seed, so "late enough to have finished" is not a number a caller
        // can know. What is being asserted is that somewhere in the cycle the run COMPLETES.
        bool finished = false;
        u32 most = 0;
        u32 total = 0;
        for (u32 step = 0; step <= 400; ++step) {
            const LogoFrame frame = logo_frame(seed, static_cast<f64>(step) * 0.1);
            INFO("seed " << seed << " algorithm " << frame.algorithm << " at " << step * 100 << " ms");
            REQUIRE(frame.algorithm < kLogoOrders);
            algorithms[frame.algorithm] = true;
            total = frame.total;
            most = std::max(most, frame.exchanges);
            CHECK(frame.exchanges <= frame.total);

            // Whatever it did, what comes out is a PERMUTATION. A drawing whose slices are not a
            // permutation has lost a stripe and grown a second copy of another one, which is the one
            // failure here that would look like a corrupt picture rather than a wrong one.
            std::vector<bool> seen(kLogoLanes, false);
            bool bijection = true;
            for (u32 at : frame.at) {
                if (at >= kLogoLanes || seen[at]) bijection = false;
                if (at < kLogoLanes) seen[at] = true;
            }
            CHECK(bijection);

            // And when the run is complete the keys are in the order that algorithm sorts them.
            // `algorithm == 0` is the one that is not an algorithm — the shuffle, held — and it says
            // so by taking no exchanges at all.
            if (frame.algorithm == 0) {
                CHECK(frame.total == 0u);
                CHECK(!frame.in_order);
                finished = true;   // a run of no exchanges is over before it starts
            } else if (frame.exchanges == frame.total) {
                CHECK(frame.in_order);
                finished = true;
            }
        }
        INFO("seed " << seed << " reached " << most << " of " << total);
        CHECK(finished);
    }
    // And every one of the ten is reachable. A count raised without a case to go with it would leave
    // a tenth of all seeds with no sort at all, and nothing would say so.
    for (u32 algorithm = 0; algorithm < kLogoOrders; ++algorithm) {
        INFO("algorithm " << algorithm);
        CHECK(algorithms[algorithm]);
    }
}

TEST_CASE("a sort in progress is a sort in progress") {
    // Pick a seed whose algorithm actually exchanges, and walk its run.
    u32 seed = 0;
    for (u32 candidate = 1; candidate < 500; ++candidate) {
        const LogoFrame frame = logo_frame(candidate, 1000.0);
        if (frame.total > 200u) {
            seed = candidate;
            break;
        }
    }
    REQUIRE(seed != 0u);
    const LogoFrame finished = logo_frame(seed, 1000.0);
    CHECK(finished.total > 200u);

    // Across a cycle the exchange count only ever goes up. It resets when the next cycle begins, and
    // the next cycle's run is a different length because it starts from a different shuffle — which is
    // the thing that makes a seed have no final state.
    u32 last = 0;
    u32 total = logo_frame(seed, 0.0).total;
    bool moved = false;
    for (i32 step = 0; step <= 40; ++step) {
        const LogoFrame frame = logo_frame(seed, static_cast<f64>(step) * 0.1);
        if (frame.total != total) {   // a new cycle, with its own shuffle and its own length
            total = frame.total;
            last = 0;
        }
        CHECK(frame.exchanges >= last);
        if (frame.exchanges > last) moved = true;
        last = frame.exchanges;
        CHECK(frame.exchanges <= frame.total);
        CHECK(frame.lane_weight >= 0.0f);
        CHECK(frame.lane_weight <= 1.0f);
        CHECK(frame.arrange_weight >= 0.0f);
        CHECK(frame.arrange_weight <= 1.0f);
    }
    CHECK(moved);

    // Deterministic in its two arguments and holding no state, so a test may ask for any instant in
    // any order — which is also what makes a scripted photograph of the mark reproducible.
    CHECK(logo_frame(seed, 3.25).at == logo_frame(seed, 3.25).at);
    CHECK(logo_frame(seed, 3.25).exchanges == logo_frame(seed, 3.25).exchanges);
}

TEST_CASE("the mark is whole for most of its cycle") {
    // A mark that is never itself is a mark nobody recognises. Both of the two things that take it
    // apart hold at nought for most of their cycles, and this is the claim measured rather than
    // asserted in a comment: over five minutes, at every seed tried, the drawing is exactly the
    // drawing for more than half the time.
    for (u32 seed : {3u, 42u, 91u, 250u, 7777u}) {
        u32 whole = 0;
        u32 both = 0;
        const u32 steps = 3000;
        for (u32 step = 0; step < steps; ++step) {
            const LogoFrame frame = logo_frame(seed, static_cast<f64>(step) * 0.1);
            if (frame.lane_weight <= 0.001f && frame.arrange_weight <= 0.001f) ++whole;
            if (frame.lane_weight > 0.1f && frame.arrange_weight > 0.1f) ++both;
        }
        INFO("seed " << seed << " whole " << whole << " of " << steps << ", both busy " << both);
        CHECK(whole > steps / 2);
        // And the two are half a cycle out of phase, so they seldom peak together.
        CHECK(both < steps / 5);
    }
}

TEST_CASE("the first mark arrives and does not morph out of nothing") {
    LogoSeed logo;
    logo.tick(10.0, false);
    CHECK(logo.seed() != 0u);
    CHECK(logo.previous() == logo.seed());
    CHECK(logo.changes() == 0u);
    // 1, not 0: at 0 the shader scatters the arriving combination into voxels and gathers it out of
    // the one before it, and there is no one before it.
    CHECK(logo.morph(10.0) == doctest::Approx(1.0f));
    CHECK(logo.age(10.0) == doctest::Approx(0.0f));
    CHECK(logo.age(12.5) == doctest::Approx(2.5f));
}

TEST_CASE("a press answers, and the change is drawn rather than cut") {
    LogoSeed logo;
    logo.tick(1.0, false);
    const u32 first = logo.seed();

    logo.change(5.0);
    CHECK(logo.seed() != first);          // a press that chose the same seed is a press that did nothing
    CHECK(logo.previous() == first);      // and the one it left is kept, because the change is drawn
    CHECK(logo.changes() == 1u);
    CHECK(logo.age(5.0) == doctest::Approx(0.0f));

    // The morph runs from nought to one over its own window and then stays there.
    CHECK(logo.morph(5.0) == doctest::Approx(0.0f));
    CHECK(logo.morph(5.0 + kLogoMorphSeconds * 0.5) > 0.4f);
    CHECK(logo.morph(5.0 + kLogoMorphSeconds * 0.5) < 0.6f);
    CHECK(logo.morph(5.0 + kLogoMorphSeconds) == doctest::Approx(1.0f));
    CHECK(logo.morph(500.0) == doctest::Approx(1.0f));
    // Eased, so the two ends of it are slower than the middle: a linear crossfade of a dissolve
    // reads as a wipe with a hard start.
    CHECK(logo.morph(5.0 + kLogoMorphSeconds * 0.1) < 0.1f);
    CHECK(logo.morph(5.0 + kLogoMorphSeconds * 0.9) > 0.9f);

    // A second press mid-morph keeps what is on screen NOW as the thing being left behind, which is
    // the combination it was arriving at.
    const u32 second = logo.seed();
    logo.change(5.5);
    CHECK(logo.previous() == second);
    CHECK(logo.changes() == 2u);
}

TEST_CASE("it changes on its own when nobody is there, and not while somebody is") {
    LogoSeed logo;
    logo.tick(0.0, false);
    const u32 first = logo.seed();

    // Somebody is here: the pointer moved a moment ago, so the clock keeps being reset and the mark
    // is left alone however long the title is up.
    for (i32 step = 1; step <= 400; ++step) {
        logo.tick(static_cast<f64>(step) * 0.5, true);
    }
    CHECK(logo.seed() == first);
    CHECK(logo.changes() == 0u);

    // Nobody is here. It changes once when the idle window is up, and then not again until another
    // whole window has passed — not every frame after it.
    f64 now = 200.0;
    logo.tick(now, true);
    for (i32 step = 0; step < 200; ++step) {
        now += 0.5;
        logo.tick(now, false);
    }
    CHECK(logo.changes() >= 1u);
    CHECK(logo.changes() <= static_cast<u64>(100.0 / kLogoIdleSeconds) + 1u);
    CHECK(logo.seed() != first);
}

TEST_CASE("a pinned seed is pinned against everything") {
    LogoSeed logo;
    logo.pin(12345u);
    CHECK(logo.pinned());
    logo.tick(0.0, false);
    CHECK(logo.seed() == 12345u);
    CHECK(logo.previous() == 12345u);
    // The morph is over before the first frame, so a photograph is of the combination and never of
    // a transition into it.
    CHECK(logo.morph(0.0) == doctest::Approx(1.0f));

    logo.change(1.0);
    CHECK(logo.seed() == 12345u);
    for (i32 step = 0; step < 400; ++step) logo.tick(static_cast<f64>(step), false);
    CHECK(logo.seed() == 12345u);
    CHECK(logo.changes() == 0u);

    // Except the one thing that is allowed to: `--logo-change`, which is how the morph is
    // photographed at all. It stays pinned afterwards, so the run is still the same run twice.
    logo.force_change(10.0);
    CHECK(logo.seed() != 12345u);
    CHECK(logo.previous() == 12345u);
    CHECK(logo.pinned());
    CHECK(logo.morph(10.0) == doctest::Approx(0.0f));
    CHECK(logo.morph(10.0 + kLogoMorphSeconds) == doctest::Approx(1.0f));
    const u32 after = logo.seed();
    for (i32 step = 0; step < 400; ++step) logo.tick(10.0 + static_cast<f64>(step), false);
    CHECK(logo.seed() == after);

    // And it is derived from the seed it left, so two runs of one command draw the same transition.
    LogoSeed again;
    again.pin(12345u);
    again.tick(0.0, false);
    again.force_change(10.0);
    CHECK(again.seed() == after);
}

TEST_CASE("the next seed is a function of its arguments and never the one it came from") {
    // Deterministic, so a scripted run draws the same picture twice; and never equal to what it
    // followed, so a press always answers.
    CHECK(logo_seed_next(7u, 3.25, 0) == logo_seed_next(7u, 3.25, 0));
    CHECK(logo_seed_next(7u, 3.25, 0) != logo_seed_next(7u, 3.25, 1));
    CHECK(logo_seed_next(7u, 3.25, 0) != logo_seed_next(8u, 3.25, 0));
    // A millisecond apart is a different mark: the clock is what makes two launches differ, and
    // rounding it to whole seconds would make every launch inside one second identical.
    CHECK(logo_seed_next(7u, 3.250, 0) != logo_seed_next(7u, 3.251, 0));

    for (u32 from = 0; from < 2000u; ++from) {
        CHECK(logo_seed_next(from, static_cast<f64>(from) * 0.01, from) != from);
    }
    // A negative clock cannot happen and must not hang the loop above if it ever does.
    CHECK(logo_seed_next(3u, -50.0, 0) != 3u);
}
