#pragma once
// How much of the mark each row and each column of the drawing holds.
//
// Generated by `tools/logo-table.ps1 -Marks` from `assets/logo.txt`, which is the same source the
// card's bitmask is packed from, and checked against that file by `tests/test_logo.cpp`.
//
// # Why the host needs this at all
//
// The drawing lives on the card as a bitmask (`shaders/logo.glsl`) and the host cannot read it. But
// the host is where the sorting happens (`src/ui/logo.hpp`, and see there for why), and one of the
// keys a seed can sort the mark's slices by is **how much mark a slice holds** -- which is a property
// of the drawing. Three hundred and twenty numbers is the whole of what the host needs to know about
// a picture it never sees.
//
// It is a count of voxels, not a fraction: a row of the drawing is 160 voxels wide, so a row holding
// ninety-nine of them is the trunk and a row holding none is the air above the canopy.

#include "core/types.hpp"

namespace ws::ui {

// --- generated: tools/logo-table.ps1 -Marks ---
inline constexpr u16 kLogoRowMark[160] = {
    0, 0, 0, 0, 0, 0, 0, 0, 14, 14, 18, 20, 26, 26, 26, 37,
    37, 41, 42, 59, 60, 60, 70, 70, 73, 74, 80, 82, 82, 84, 84, 87,
    87, 87, 89, 89, 89, 89, 91, 91, 92, 94, 94, 98, 98, 99, 90, 91,
    92, 82, 82, 81, 81, 75, 80, 86, 79, 85, 83, 87, 75, 76, 76, 68,
    70, 53, 60, 43, 48, 50, 46, 53, 51, 64, 53, 55, 49, 48, 43, 38,
    38, 29, 29, 25, 25, 22, 15, 16, 10, 10, 11, 12, 12, 12, 14, 14,
    14, 14, 17, 17, 17, 21, 21, 21, 21, 27, 35, 35, 55, 56, 76, 53,
    83, 71, 56, 82, 78, 85, 57, 70, 68, 37, 51, 39, 75, 57, 67, 38,
    29, 38, 33, 46, 34, 44, 45, 43, 48, 30, 30, 18, 27, 27, 19, 28,
    23, 26, 18, 18, 13, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
};

inline constexpr u16 kLogoColumnMark[160] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 14, 23, 23, 28,
    30, 34, 36, 36, 48, 48, 51, 48, 53, 66, 66, 77, 72, 72, 71, 83,
    90, 82, 83, 76, 79, 68, 75, 73, 73, 75, 68, 70, 67, 72, 79, 80,
    83, 69, 68, 65, 77, 79, 72, 91, 83, 87, 84, 92, 100, 99, 108, 105,
    118, 118, 124, 116, 116, 115, 106, 110, 99, 116, 106, 104, 93, 78, 79, 63,
    65, 73, 81, 69, 59, 58, 54, 59, 58, 63, 69, 61, 59, 48, 54, 54,
    59, 71, 66, 61, 50, 52, 52, 55, 52, 47, 47, 47, 49, 46, 46, 38,
    35, 37, 30, 33, 27, 26, 18, 14, 12, 6, 6, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
};

// --- end generated ---

}  // namespace ws::ui
