#!/usr/bin/env bash
# Build tools/clipcheck and run it. See the header of tools/clipcheck.cpp for why it exists.
#
#   tools/clipcheck.sh clips/facility.clip --part part_portico --metre 8
#
# It compiles once into build/clipcheck and reuses it; pass `rebuild` as the first argument to
# force it. Nothing here needs Vulkan, SDL or Windows — ws_forge depends on the standard library
# and on ws_core/ws_world/ws_game, and none of those know what a graphics device is.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="$root/build/clipcheck"
gen="$root/build/generated"

force=0
if [[ "${1:-}" == "rebuild" ]]; then force=1; shift; fi

newest=$(find "$root/src/core" "$root/src/world" "$root/src/game" "$root/src/forge" \
              "$root/tools/clipcheck.cpp" -newer "$out" -print -quit 2>/dev/null || true)
if [[ $force -eq 1 || ! -x "$out" || -n "$newest" ]]; then
    mkdir -p "$gen/core" "$root/build"
    # version.hpp is generated by CMake from the project version; do the same substitution here so
    # this does not need a configure step.
    ver=$(sed -n 's/^project(WorldShaper VERSION \([0-9.]*\).*/\1/p' "$root/CMakeLists.txt")
    IFS=. read -r vmaj vmin vpat <<< "$ver"
    sed -e "s/@PROJECT_VERSION_MAJOR@/${vmaj:-0}/g" \
        -e "s/@PROJECT_VERSION_MINOR@/${vmin:-0}/g" \
        -e "s/@PROJECT_VERSION_PATCH@/${vpat:-0}/g" \
        -e "s/@PROJECT_VERSION@/$ver/g" \
        "$root/src/core/version.hpp.in" > "$gen/core/version.hpp"

    echo "clipcheck: compiling..." >&2
    # -O2 and not -O0: the facility is 580 million cells and an unoptimised sampler turns a
    # twenty-second check into something nobody runs twice.
    g++ -std=c++20 -O2 -DWS_DEBUG=0 -Wno-missing-field-initializers \
        -I"$root/src" -I"$gen" \
        "$root/tools/clipcheck.cpp" \
        "$root"/src/core/*.cpp "$root"/src/world/*.cpp "$root"/src/game/*.cpp \
        "$root"/src/forge/*.cpp \
        -o "$out" -pthread
fi

exec "$out" "$@"
