#!/usr/bin/env bash
# Build tools/paintcheck and run it. See the header of tools/paintcheck.cpp for why it exists.
#
#   tools/paintcheck.sh clips/sampler.clip
#   tools/paintcheck.sh clips/facility.clip --part part_portico --metre 8
#   tools/paintcheck.sh clips/sampler.clip --wsc web/data/sampler.wsc
#
# Built the way tools/clipcheck.sh is built, and for the same reason: nothing in it needs Vulkan,
# SDL or Windows. `ws_forge` depends on the standard library and on ws_core/ws_world/ws_game, and
# none of those know what a graphics device is — so the agreement between the sampler and the raw
# view is checkable on any machine, in a script, rather than by squinting at two screenshots.
#
# It compiles once into build/paintcheck and reuses it; pass `rebuild` as the first argument to
# force it.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="$root/build/paintcheck"
gen="$root/build/generated"

force=0
if [[ "${1:-}" == "rebuild" ]]; then force=1; shift; fi

newest=$(find "$root/src/core" "$root/src/world" "$root/src/game" "$root/src/forge" \
              "$root/tools/paintcheck.cpp" -newer "$out" -print -quit 2>/dev/null || true)
if [[ $force -eq 1 || ! -x "$out" || -n "$newest" ]]; then
    mkdir -p "$gen/core" "$root/build"
    # version.hpp is generated by CMake from the project version; do the same substitution here so
    # this does not need a configure step.
    ver=$(sed -n 's/^project(WorldShaper VERSION \([0-9.]*\).*/\1/p' "$root/CMakeLists.txt")
    IFS=. read -r vmaj vmin vpat <<< "$ver"
    sed -e "s/@PROJECT_VERSION_MAJOR@/${vmaj:-0}/g" \
        -e "s/@PROJECT_VERSION_MINOR@/${vmin:-0}/g" \
        -e "s/@PROJECT_VERSION_PATCH@/${vpat:-0}/g" \
        -e "s/@PROJECT_VERSION@/$ver/g" \
        "$root/src/core/version.hpp.in" > "$gen/core/version.hpp"

    echo "paintcheck: compiling..." >&2
    # -O2 for the same reason clipcheck is: this walks the paint stack five times at every surface
    # voxel, and an unoptimised walk turns a check into something nobody runs twice.
    g++ -std=c++20 -O2 -DWS_DEBUG=0 -Wall -Wextra -Wno-missing-field-initializers \
        -Wno-unused-parameter \
        -I"$root/src" -I"$gen" \
        "$root/tools/paintcheck.cpp" \
        "$root"/src/core/*.cpp "$root"/src/world/*.cpp "$root"/src/game/*.cpp \
        "$root"/src/forge/*.cpp \
        -o "$out" -pthread
fi

exec "$out" "$@"
